//! Clippy suppression audit.
//!
//! Collects every clippy lint the workspace suppresses, from `#[allow]`,
//! `#![allow]`, `#[expect]` and `#[cfg_attr(.., allow|expect(..))]`
//! attributes in Rust sources and from `"allow"` levels in the
//! `[lints.clippy]` and `[workspace.lints.clippy]` manifest tables, and
//! compares the result with a checked-in baseline. The audit counts
//! suppression sites per file and lint: a count above the baseline is a new
//! suppression and fails, and a count below it is a stale baseline entry that
//! must be shrunk with `--write`, so a removed suppression cannot return.

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

/// Attribute names whose argument list suppresses lints.
const SUPPRESSING_ATTRS: [&str; 2] = ["allow", "expect"];

/// One suppressed lint in one file, rendered as `<path> clippy::<lint>`.
pub type Suppression = String;

/// Suppression sites per lint name within one source.
pub type LintCounts = BTreeMap<String, usize>;

/// Every suppression found, with its number of sites, sorted.
pub type Suppressions = BTreeMap<Suppression, usize>;

/// Difference between the suppressions found and the baseline, one rendered
/// line per entry (`<path> clippy::<lint>: <found> vs <baseline>`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AuditDiff {
    /// Entries with more sites in the tree than the baseline allows.
    pub added: Vec<String>,
    /// Entries with fewer sites in the tree than the baseline lists.
    pub stale: Vec<String>,
}

/// Returns the clippy lints suppressed by attributes in Rust `source`.
///
/// Comment lines (including doc comments) and string literals are ignored,
/// so documentation or test fixtures that show an attribute do not count as
/// a suppression.
#[must_use]
pub fn scan_rust_source(source: &str) -> LintCounts {
    let uncommented: String = source
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n");
    let code = strip_string_literals(&uncommented);

    let mut lints = LintCounts::new();
    for (idx, _) in code.match_indices('#') {
        let Some(after) = code.get(idx..).and_then(|tail| {
            tail.strip_prefix("#[").or_else(|| tail.strip_prefix("#!["))
        }) else {
            continue;
        };
        let body = attribute_body(after);
        if suppresses(body) {
            for lint in clippy_lints(body) {
                let n = lints.entry(lint).or_insert(0);
                *n = n.saturating_add(1);
            }
        }
    }
    lints
}

/// Returns the clippy lints set to `"allow"` in a manifest's
/// `[lints.clippy]` or `[workspace.lints.clippy]` table.
#[must_use]
pub fn scan_manifest(manifest: &str) -> LintCounts {
    let mut lints = LintCounts::new();
    let mut in_clippy_table = false;
    for line in manifest.lines().map(str::trim) {
        if line.starts_with('[') {
            in_clippy_table =
                line == "[lints.clippy]" || line == "[workspace.lints.clippy]";
            continue;
        }
        if in_clippy_table
            && let Some((name, value)) = line.split_once('=')
            && value.contains("\"allow\"")
        {
            let n = lints.entry(name.trim().to_string()).or_insert(0);
            *n = n.saturating_add(1);
        }
    }
    lints
}

/// Collects every suppression under `root`, skipping `target` and hidden
/// directories. Paths are relative to `root` with `/` separators.
///
/// # Errors
///
/// Returns an I/O error if a directory or file cannot be read.
pub fn collect(root: &Path) -> io::Result<Suppressions> {
    let mut found = Suppressions::new();
    visit(root, root, &mut found)?;
    Ok(found)
}

/// Parses a baseline file: one `<path> clippy::<lint> <count>` per line.
///
/// `#` comments and blank lines are ignored. A line without a count (the format
/// before counts were recorded) allows any number of sites, so an old
/// baseline read through `--base-ref` still bounds which entries exist.
#[must_use]
pub fn parse_baseline(text: &str) -> Suppressions {
    let mut out = Suppressions::new();
    for line in text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
    {
        let (entry, count) = match line.rsplit_once(' ') {
            Some((head, tail)) if tail.parse::<usize>().is_ok() => {
                (head.trim(), tail.parse().unwrap_or(usize::MAX))
            }
            _ => (line, usize::MAX),
        };
        let n = out.entry(entry.to_string()).or_insert(0);
        *n = n.saturating_add(count);
    }
    out
}

/// Renders suppressions as a baseline file.
#[must_use]
pub fn render_baseline(found: &Suppressions) -> String {
    let mut out = String::from(
        "# Clippy suppressions that predate the allow audit.\n\
         # Generated by `cargo run -p control-rs-ci --bin allow-audit -- --write`.\n\
         # Format: <path> clippy::<lint> <sites>. Counts may only shrink.\n",
    );
    for (entry, count) in found {
        out.push_str(entry);
        out.push(' ');
        out.push_str(&count.to_string());
        out.push('\n');
    }
    out
}

/// Entries whose count in `current` exceeds their count in `base`, rendered
/// as in [`AuditDiff`]. Used to check that a branch did not grow the
/// baseline relative to its merge target.
#[must_use]
pub fn growth(current: &Suppressions, base: &Suppressions) -> Vec<String> {
    current
        .iter()
        .filter_map(|(entry, &count)| {
            let allowed = base.get(entry).copied().unwrap_or(0);
            (count > allowed).then(|| format!("{entry}: {count} vs {allowed}"))
        })
        .collect()
}

/// Compares the suppressions `found` with `baseline`.
#[must_use]
pub fn diff(found: &Suppressions, baseline: &Suppressions) -> AuditDiff {
    AuditDiff {
        added: growth(found, baseline),
        stale: growth(baseline, found),
    }
}

/// `code` with the contents of every string literal removed, including raw
/// strings (`r"..."`, `r#"..."#`). Char literals such as `'"'` are kept
/// intact and do not open a string.
fn strip_string_literals(code: &str) -> String {
    let mut out = String::with_capacity(code.len());
    let mut chars = code.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\'' => {
                out.push(c);
                // A char literal holding a quote: keep it, open no string.
                if chars.peek() == Some(&'"') {
                    out.extend(chars.next());
                }
            }
            'r' if matches!(chars.peek(), Some('"' | '#')) => {
                let mut hashes = 0_usize;
                while chars.next_if_eq(&'#').is_some() {
                    hashes = hashes.saturating_add(1);
                }
                if chars.next_if_eq(&'"').is_none() {
                    // `r#ident` raw identifier, not a string.
                    out.push('r');
                    out.extend(std::iter::repeat_n('#', hashes));
                    continue;
                }
                skip_raw_string(&mut chars, hashes);
                out.push_str("\"\"");
            }
            '"' => {
                while let Some(inner) = chars.next() {
                    match inner {
                        '\\' => {
                            chars.next();
                        }
                        '"' => break,
                        _ => {}
                    }
                }
                out.push_str("\"\"");
            }
            _ => out.push(c),
        }
    }
    out
}

/// Advances past the body of a raw string with `hashes` `#` delimiters.
fn skip_raw_string(
    chars: &mut std::iter::Peekable<std::str::Chars<'_>>,
    hashes: usize,
) {
    while let Some(c) = chars.next() {
        if c == '"' {
            let mut closing = 0_usize;
            while closing < hashes && chars.next_if_eq(&'#').is_some() {
                closing = closing.saturating_add(1);
            }
            if closing == hashes {
                return;
            }
        }
    }
}

/// Text inside the brackets of the attribute that starts `rest`, up to the
/// matching `]`.
fn attribute_body(rest: &str) -> &str {
    let mut depth = 0_usize;
    for (idx, ch) in rest.char_indices() {
        match ch {
            '[' | '(' => depth = depth.saturating_add(1),
            ']' | ')' if depth > 0 => depth = depth.saturating_sub(1),
            ']' => return rest.get(..idx).unwrap_or(rest),
            _ => {}
        }
    }
    rest
}

/// Whether an attribute body is `allow(..)`, `expect(..)` or a `cfg_attr`
/// that applies one of them.
fn suppresses(body: &str) -> bool {
    let body = body.trim_start();
    let is_call = |name: &str| {
        body.strip_prefix(name)
            .is_some_and(|tail| tail.trim_start().starts_with('('))
    };
    SUPPRESSING_ATTRS.iter().any(|name| is_call(name))
        || (is_call("cfg_attr")
            && SUPPRESSING_ATTRS
                .iter()
                .any(|name| body.contains(&format!("{name}("))))
}

/// Every `clippy::<lint>` path named in `body`.
fn clippy_lints(body: &str) -> impl Iterator<Item = String> + '_ {
    body.split("clippy::").skip(1).filter_map(|tail| {
        let name: String = tail
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        (!name.is_empty()).then_some(name)
    })
}

/// Recursively scans `dir`, recording suppressions relative to `root`.
fn visit(root: &Path, dir: &Path, found: &mut Suppressions) -> io::Result<()> {
    let mut entries: Vec<_> =
        fs::read_dir(dir)?.collect::<io::Result<Vec<_>>>()?;
    entries.sort_by_key(fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if path.is_dir() {
            if name != "target" && !name.starts_with('.') {
                visit(root, &path, found)?;
            }
            continue;
        }
        let lints = if name.ends_with(".rs") {
            scan_rust_source(&fs::read_to_string(&path)?)
        } else if name == "Cargo.toml" {
            scan_manifest(&fs::read_to_string(&path)?)
        } else {
            continue;
        };
        let rel = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        for (lint, count) in lints {
            let n = found.entry(format!("{rel} clippy::{lint}")).or_insert(0);
            *n = n.saturating_add(count);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Suppression entries with their site counts.
    type Entries<'a> = &'a [(&'a str, usize)];

    #[test]
    fn finds_outer_inner_and_expect_attributes() {
        let src = "#![allow(clippy::too_many_lines)]\n\
                   #[allow(clippy::indexing_slicing, missing_docs)]\n\
                   fn a() {}\n\
                   #[expect(clippy::unwrap_used, reason = \"x\")]\n\
                   fn b() {}\n";
        let lints: Vec<_> = scan_rust_source(src).into_keys().collect();
        assert_eq!(
            lints,
            ["indexing_slicing", "too_many_lines", "unwrap_used"]
        );
    }

    #[test]
    fn finds_multi_line_and_cfg_attr_allows() {
        let src = "#![allow(\n    clippy::cast_lossless,\n    clippy::panic\n)]\n\
                   #[cfg_attr(feature = \"ets\", allow(clippy::unwrap_used))]\n\
                   mod m {}\n";
        let lints: Vec<_> = scan_rust_source(src).into_keys().collect();
        assert_eq!(lints, ["cast_lossless", "panic", "unwrap_used"]);
    }

    #[test]
    fn ignores_other_attributes_and_comments() {
        let src = "#[derive(Debug)]\n\
                   #[cfg_attr(test, derive(Clone))]\n\
                   /// Example: `#[allow(clippy::panic)]`\n\
                   // #[allow(clippy::unwrap_used)]\n\
                   #[deny(clippy::panic)]\n\
                   struct S;\n";
        assert!(scan_rust_source(src).is_empty());
    }

    #[test]
    fn ignores_attributes_inside_string_literals() {
        let src = r##"
            const A: &str = "#[allow(clippy::panic)]";
            const B: &str = r#"#![allow(clippy::unwrap_used)]"#;
            const Q: char = '"';
            #[allow(clippy::indexing_slicing)]
            fn f() {}
        "##;
        let lints: Vec<_> = scan_rust_source(src).into_keys().collect();
        assert_eq!(lints, ["indexing_slicing"]);
    }

    #[test]
    fn manifest_allow_levels_are_found() {
        let manifest = "[workspace.lints.clippy]\n\
                        inline_always = { level = \"allow\", priority = 1 }\n\
                        todo = { level = \"warn\", priority = 1 }\n\
                        pedantic = \"deny\"\n\
                        [dependencies]\n\
                        allow = \"allow\"\n";
        let lints: Vec<_> = scan_manifest(manifest).into_keys().collect();
        assert_eq!(lints, ["inline_always"]);
    }

    fn sup(entries: Entries<'_>) -> Suppressions {
        entries
            .iter()
            .map(|(e, c)| ((*e).to_string(), *c))
            .collect()
    }

    #[test]
    fn diff_separates_added_and_stale() {
        let found = sup(&[("a.rs clippy::x", 1), ("b.rs clippy::y", 1)]);
        let baseline = sup(&[("a.rs clippy::x", 1), ("c.rs clippy::z", 1)]);
        let result = diff(&found, &baseline);
        assert_eq!(result.added, ["b.rs clippy::y: 1 vs 0"]);
        assert_eq!(result.stale, ["c.rs clippy::z: 1 vs 0"]);
    }

    #[test]
    fn counts_new_sites_of_a_baselined_lint() {
        let src = "#[allow(clippy::panic)]\nfn a() {}\n\
                   #[allow(clippy::panic)]\nfn b() {}\n";
        assert_eq!(scan_rust_source(src).get("panic"), Some(&2));
        let found = sup(&[("a.rs clippy::panic", 2)]);
        let baseline = sup(&[("a.rs clippy::panic", 1)]);
        assert_eq!(
            diff(&found, &baseline).added,
            ["a.rs clippy::panic: 2 vs 1"]
        );
        assert!(diff(&baseline, &baseline).stale.is_empty());
        assert_eq!(
            diff(&baseline, &found).stale,
            ["a.rs clippy::panic: 2 vs 1"]
        );
    }

    #[test]
    fn baseline_round_trips_and_reads_countless_lines() {
        let found = sup(&[("a.rs clippy::x", 3), ("b.rs clippy::y", 1)]);
        assert_eq!(parse_baseline(&render_baseline(&found)), found);
        assert_eq!(
            parse_baseline("# c\na.rs clippy::x\n"),
            sup(&[("a.rs clippy::x", usize::MAX)])
        );
    }

    #[test]
    fn growth_against_base_ref() {
        let base = sup(&[("a.rs clippy::x", 2)]);
        let current = sup(&[("a.rs clippy::x", 2), ("b.rs clippy::y", 1)]);
        assert_eq!(growth(&current, &base), ["b.rs clippy::y: 1 vs 0"]);
        assert!(growth(&base, &base).is_empty());
    }
}
