//! Clippy suppression audit.
//!
//! Collects every clippy lint the workspace suppresses, from `#[allow]`,
//! `#![allow]`, `#[expect]` and `#[cfg_attr(.., allow|expect(..))]`
//! attributes in Rust sources and from `"allow"` levels in the
//! `[lints.clippy]` and `[workspace.lints.clippy]` manifest tables, and
//! compares the result with a checked-in baseline. Any suppression that the
//! baseline does not list is a new suppression and fails the audit.

use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::Path;

/// Attribute names whose argument list suppresses lints.
const SUPPRESSING_ATTRS: [&str; 2] = ["allow", "expect"];

/// One suppressed lint in one file, rendered as `<path> clippy::<lint>`.
pub type Suppression = String;

/// Every suppression found, sorted.
pub type Suppressions = BTreeSet<Suppression>;

/// Difference between the suppressions found and the baseline.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AuditDiff {
    /// Suppressions present in the tree but not in the baseline.
    pub added: Vec<Suppression>,
    /// Baseline entries no longer present in the tree.
    pub stale: Vec<Suppression>,
}

/// Returns the clippy lints suppressed by attributes in Rust `source`.
///
/// Comment lines (including doc comments) and string literals are ignored,
/// so documentation or test fixtures that show an attribute do not count as
/// a suppression.
#[must_use]
pub fn scan_rust_source(source: &str) -> BTreeSet<String> {
    let uncommented: String = source
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n");
    let code = strip_string_literals(&uncommented);

    let mut lints = BTreeSet::new();
    for (idx, _) in code.match_indices('#') {
        let Some(after) = code.get(idx..).and_then(|tail| {
            tail.strip_prefix("#[").or_else(|| tail.strip_prefix("#!["))
        }) else {
            continue;
        };
        let body = attribute_body(after);
        if suppresses(body) {
            lints.extend(clippy_lints(body));
        }
    }
    lints
}

/// Returns the clippy lints set to `"allow"` in a manifest's
/// `[lints.clippy]` or `[workspace.lints.clippy]` table.
#[must_use]
pub fn scan_manifest(manifest: &str) -> BTreeSet<String> {
    let mut lints = BTreeSet::new();
    let mut in_clippy_table = false;
    for line in manifest.lines().map(str::trim) {
        if line.starts_with('[') {
            in_clippy_table =
                line == "[lints.clippy]" || line == "[workspace.lints.clippy]";
            continue;
        }
        if in_clippy_table
            && let Some((name, value)) = line.split_once('=')
            && value.contains("\"allow\"")
        {
            lints.insert(name.trim().to_string());
        }
    }
    lints
}

/// Collects every suppression under `root`, skipping `target` and hidden
/// directories. Paths are relative to `root` with `/` separators.
///
/// # Errors
///
/// Returns an I/O error if a directory or file cannot be read.
pub fn collect(root: &Path) -> io::Result<Suppressions> {
    let mut found = Suppressions::new();
    visit(root, root, &mut found)?;
    Ok(found)
}

/// Parses a baseline file: one suppression per line, `#` comments and blank
/// lines ignored.
#[must_use]
pub fn parse_baseline(text: &str) -> Suppressions {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_string)
        .collect()
}

/// Renders suppressions as a baseline file.
#[must_use]
pub fn render_baseline(found: &Suppressions) -> String {
    let mut out = String::from(
        "# Clippy suppressions that predate the allow audit.\n\
         # Generated by `cargo run -p control-rs-ci --bin allow-audit -- --write`.\n\
         # Entries may only be removed. Every new suppression fails the audit.\n",
    );
    for entry in found {
        out.push_str(entry);
        out.push('\n');
    }
    out
}

/// Compares the suppressions `found` with `baseline`.
#[must_use]
pub fn diff(found: &Suppressions, baseline: &Suppressions) -> AuditDiff {
    AuditDiff {
        added: found.difference(baseline).cloned().collect(),
        stale: baseline.difference(found).cloned().collect(),
    }
}

/// `code` with the contents of every string literal removed, including raw
/// strings (`r"..."`, `r#"..."#`). Char literals such as `'"'` are kept
/// intact and do not open a string.
fn strip_string_literals(code: &str) -> String {
    let mut out = String::with_capacity(code.len());
    let mut chars = code.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\'' => {
                out.push(c);
                // A char literal holding a quote: keep it, open no string.
                if chars.peek() == Some(&'"') {
                    out.extend(chars.next());
                }
            }
            'r' if matches!(chars.peek(), Some('"' | '#')) => {
                let mut hashes = 0_usize;
                while chars.next_if_eq(&'#').is_some() {
                    hashes = hashes.saturating_add(1);
                }
                if chars.next_if_eq(&'"').is_none() {
                    // `r#ident` raw identifier, not a string.
                    out.push('r');
                    out.extend(std::iter::repeat_n('#', hashes));
                    continue;
                }
                skip_raw_string(&mut chars, hashes);
                out.push_str("\"\"");
            }
            '"' => {
                while let Some(inner) = chars.next() {
                    match inner {
                        '\\' => {
                            chars.next();
                        }
                        '"' => break,
                        _ => {}
                    }
                }
                out.push_str("\"\"");
            }
            _ => out.push(c),
        }
    }
    out
}

/// Advances past the body of a raw string with `hashes` `#` delimiters.
fn skip_raw_string(
    chars: &mut std::iter::Peekable<std::str::Chars<'_>>,
    hashes: usize,
) {
    while let Some(c) = chars.next() {
        if c == '"' {
            let mut closing = 0_usize;
            while closing < hashes && chars.next_if_eq(&'#').is_some() {
                closing = closing.saturating_add(1);
            }
            if closing == hashes {
                return;
            }
        }
    }
}

/// Text inside the brackets of the attribute that starts `rest`, up to the
/// matching `]`.
fn attribute_body(rest: &str) -> &str {
    let mut depth = 0_usize;
    for (idx, ch) in rest.char_indices() {
        match ch {
            '[' | '(' => depth = depth.saturating_add(1),
            ']' | ')' if depth > 0 => depth = depth.saturating_sub(1),
            ']' => return rest.get(..idx).unwrap_or(rest),
            _ => {}
        }
    }
    rest
}

/// Whether an attribute body is `allow(..)`, `expect(..)` or a `cfg_attr`
/// that applies one of them.
fn suppresses(body: &str) -> bool {
    let body = body.trim_start();
    let is_call = |name: &str| {
        body.strip_prefix(name)
            .is_some_and(|tail| tail.trim_start().starts_with('('))
    };
    SUPPRESSING_ATTRS.iter().any(|name| is_call(name))
        || (is_call("cfg_attr")
            && SUPPRESSING_ATTRS
                .iter()
                .any(|name| body.contains(&format!("{name}("))))
}

/// Every `clippy::<lint>` path named in `body`.
fn clippy_lints(body: &str) -> impl Iterator<Item = String> + '_ {
    body.split("clippy::").skip(1).filter_map(|tail| {
        let name: String = tail
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        (!name.is_empty()).then_some(name)
    })
}

/// Recursively scans `dir`, recording suppressions relative to `root`.
fn visit(root: &Path, dir: &Path, found: &mut Suppressions) -> io::Result<()> {
    let mut entries: Vec<_> =
        fs::read_dir(dir)?.collect::<io::Result<Vec<_>>>()?;
    entries.sort_by_key(fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if path.is_dir() {
            if name != "target" && !name.starts_with('.') {
                visit(root, &path, found)?;
            }
            continue;
        }
        let lints = if name.ends_with(".rs") {
            scan_rust_source(&fs::read_to_string(&path)?)
        } else if name == "Cargo.toml" {
            scan_manifest(&fs::read_to_string(&path)?)
        } else {
            continue;
        };
        let rel = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        found.extend(
            lints
                .into_iter()
                .map(|lint| format!("{rel} clippy::{lint}")),
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_outer_inner_and_expect_attributes() {
        let src = "#![allow(clippy::too_many_lines)]\n\
                   #[allow(clippy::indexing_slicing, missing_docs)]\n\
                   fn a() {}\n\
                   #[expect(clippy::unwrap_used, reason = \"x\")]\n\
                   fn b() {}\n";
        let lints: Vec<_> = scan_rust_source(src).into_iter().collect();
        assert_eq!(
            lints,
            ["indexing_slicing", "too_many_lines", "unwrap_used"]
        );
    }

    #[test]
    fn finds_multi_line_and_cfg_attr_allows() {
        let src = "#![allow(\n    clippy::cast_lossless,\n    clippy::panic\n)]\n\
                   #[cfg_attr(feature = \"ets\", allow(clippy::unwrap_used))]\n\
                   mod m {}\n";
        let lints: Vec<_> = scan_rust_source(src).into_iter().collect();
        assert_eq!(lints, ["cast_lossless", "panic", "unwrap_used"]);
    }

    #[test]
    fn ignores_other_attributes_and_comments() {
        let src = "#[derive(Debug)]\n\
                   #[cfg_attr(test, derive(Clone))]\n\
                   /// Example: `#[allow(clippy::panic)]`\n\
                   // #[allow(clippy::unwrap_used)]\n\
                   #[deny(clippy::panic)]\n\
                   struct S;\n";
        assert!(scan_rust_source(src).is_empty());
    }

    #[test]
    fn ignores_attributes_inside_string_literals() {
        let src = r##"
            const A: &str = "#[allow(clippy::panic)]";
            const B: &str = r#"#![allow(clippy::unwrap_used)]"#;
            const Q: char = '"';
            #[allow(clippy::indexing_slicing)]
            fn f() {}
        "##;
        let lints: Vec<_> = scan_rust_source(src).into_iter().collect();
        assert_eq!(lints, ["indexing_slicing"]);
    }

    #[test]
    fn manifest_allow_levels_are_found() {
        let manifest = "[workspace.lints.clippy]\n\
                        inline_always = { level = \"allow\", priority = 1 }\n\
                        todo = { level = \"warn\", priority = 1 }\n\
                        pedantic = \"deny\"\n\
                        [dependencies]\n\
                        allow = \"allow\"\n";
        let lints: Vec<_> = scan_manifest(manifest).into_iter().collect();
        assert_eq!(lints, ["inline_always"]);
    }

    #[test]
    fn diff_separates_added_and_stale() {
        let found: Suppressions = ["a.rs clippy::x", "b.rs clippy::y"]
            .map(String::from)
            .into();
        let baseline: Suppressions = ["a.rs clippy::x", "c.rs clippy::z"]
            .map(String::from)
            .into();
        let result = diff(&found, &baseline);
        assert_eq!(result.added, ["b.rs clippy::y"]);
        assert_eq!(result.stale, ["c.rs clippy::z"]);
    }

    #[test]
    fn baseline_round_trips() {
        let found: Suppressions = ["a.rs clippy::x", "b.rs clippy::y"]
            .map(String::from)
            .into();
        assert_eq!(parse_baseline(&render_baseline(&found)), found);
    }
}
