#!/usr/bin/env python3
"""
plot_dc_motor.py

Diagnostic visualizer for the DC motor armature classical control example:
- Peripheral delay (tau_act = 500 us)
- Noisy actuator (voltage noise + saturation)
- Delayed & noisy 16-bit absolute position encoder (tau_sens = 500 us, 65,536 counts/turn)
- Dual Rust controller comparison: Controller A (Lead via DirectForm2T) vs Controller B (PID) vs Ideal Baseline

Loads `results/dc-motor.*.h5` generated by `cargo run` and renders a 4-panel dark-themed dashboard:
  1. Frequency Response (Bode magnitude, plant phase, loop delay penalty, and compensated loop)
  2. Root Locus Trajectory (Z-plane pole migration over loop gain sweep)
  3. Closed-Loop Position Tracking (Ideal vs Lead vs PID with 16-bit quantization & noise)
  4. Actuator Effort & Armature Current (Terminal voltage saturation and current response)

Usage:
  python3 plot_dc_motor.py [--show] [--json <path>] [--output <path>]
"""

import sys
from pathlib import Path

import matplotlib.patches as patches
import matplotlib.pyplot as plt
import numpy as np

# Ensure shared python3 directory is on sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent))

from control_rs_plot import (
    BG_COLOR,
    COLOR_ASYMPTOTE,
    COLOR_CRIT,
    COLOR_GREEN,
    COLOR_ORANGE,
    COLOR_PRIMARY,
    COLOR_QUATERNARY,
    COLOR_SECONDARY,
    COLOR_TARGET,
    COLOR_TERTIARY,
    COLOR_WHITE,
    GRID_COLOR,
    PANEL_BG,
    SUBDUED_TEXT,
    TEXT_COLOR,
    apply_theme,
    resolve_results_path,
    save_or_show,
    setup_argument_parser,
    load_plot_container,
)


def plot_frequency_response(ax_mag, ax_phase, data: dict):
    """Bode plot showing plant, delay penalty, and compensated loop."""
    freq_data = data["analysis"]["frequency_sweep"]
    omegas = np.array(freq_data["omegas"])
    plant_mag = np.array(freq_data["plant_mag_db"])
    plant_phase = np.rad2deg(np.unwrap(np.deg2rad(np.array(freq_data["plant_phase_deg"]))))
    loop_mag = np.array(freq_data["loop_mag_db"])
    loop_phase = np.rad2deg(np.unwrap(np.deg2rad(np.array(freq_data["loop_phase_deg"]))))
    delay_phase = np.array(freq_data["delay_phase_deg"])
    delayed_plant_phase = plant_phase + delay_phase

    comp_margins = data["analysis"]["compensated_margins"]
    wc = comp_margins.get("gain_crossover_rad_s", 50.0)
    pm = comp_margins.get("phase_margin_deg", 50.0)

    # Magnitude: loop first (Primary), plant second (Secondary)
    ax_mag.semilogx(omegas, loop_mag, linewidth=1.3, label=r"Compensated $L(s) = C(s)G(s)$")
    ax_mag.semilogx(omegas, plant_mag, linewidth=1.2, label=r"Plant $G_{v\theta}(s)$", alpha=0.85)
    ax_mag.axhline(0, color=COLOR_ASYMPTOTE, linestyle=":", linewidth=0.9, alpha=0.5, label="0 dB Crossover")
    if wc:
        ax_mag.axvline(wc, color=COLOR_PRIMARY, linestyle=":", linewidth=1.1, alpha=0.7)

    gm_val = comp_margins.get("gain_margin_db")
    gm_str = f"GM: {gm_val:.1f} dB" if gm_val is not None else "GM: unbounded (no −180° crossing)"
    ax_mag.text(
        0.03,
        0.10,
        gm_str,
        transform=ax_mag.transAxes,
        fontsize=6.5,
        fontweight="bold",
        color=TEXT_COLOR,
        bbox=dict(
            boxstyle="round,pad=0.25",
            facecolor=PANEL_BG,
            edgecolor=GRID_COLOR,
            alpha=0.9,
        ),
    )

    ax_mag.set_ylabel("Magnitude (dB)")
    ax_mag.set_title("Frequency Response & Delay Phase Penalty", loc="left", pad=8, fontweight="bold")
    ax_mag.legend(loc="upper right", fontsize=6.8)
    ax_mag.set_xlim(1.0, 1000.0)
    plt.setp(ax_mag.get_xticklabels(), visible=False)

    # Phase: loop first (Primary), plant second (Secondary), delayed plant third (Tertiary)
    ax_phase.semilogx(omegas, loop_phase, linewidth=1.3, label=r"Compensated $\angle L(j\omega)$")
    ax_phase.semilogx(omegas, plant_phase, linewidth=1.2, label=r"Plant $\angle G(j\omega)$", alpha=0.85)
    ax_phase.semilogx(omegas, delayed_plant_phase, linewidth=1.1, linestyle="--",
                      label=r"Delayed Plant $\angle G - \omega \tau_d$", alpha=0.85)
    ax_phase.axhline(-180, color=COLOR_CRIT, linestyle=":", linewidth=0.9, alpha=0.7, label=r"$-180^\circ$ Threshold")

    if wc and pm:
        ax_phase.axvline(wc, color=COLOR_PRIMARY, linestyle=":", linewidth=1.1, alpha=0.7)
        ax_phase.annotate(
            f"$\\omega_{{gc}} = {wc:.1f}$ rad/s\n$\\Phi_m = {pm:.1f}^\\circ$",
            xy=(wc, -180 + pm),
            xytext=(15.0, -45.0),
            arrowprops=dict(facecolor=COLOR_PRIMARY, edgecolor=COLOR_PRIMARY, shrink=0.08, width=1.0, headwidth=5),
            color=TEXT_COLOR,
            fontweight="bold",
            fontsize=6.5,
            bbox=dict(boxstyle="round,pad=0.15", facecolor=PANEL_BG, edgecolor=GRID_COLOR, alpha=0.9),
        )

    ax_phase.set_xlabel("Frequency (rad/s)")
    ax_phase.set_ylabel("Phase (deg)")
    ax_phase.legend(loc="upper right", fontsize=6.8)
    ax_phase.set_xlim(1.0, 1000.0)
    ax_phase.set_ylim(-260, 0)


def plot_root_locus(ax, data: dict, py_locus: dict | None = None):
    """Z-plane root locus trajectory with zoomed main view near z = 1 and full unit circle thumbnail."""
    rl_data = data["analysis"]["root_locus"]
    re_poles = np.array(rl_data["poles_re"])
    im_poles = np.array(rl_data["poles_im"])
    ts = data.get("peripherals", {}).get("ts_s", 0.0005)

    s_poles = re_poles + 1j * im_poles
    z_poles = np.exp(s_poles * ts)
    z_re = z_poles.real
    z_im = z_poles.imag

    theta_circ = np.linspace(0, 2 * np.pi, 500)

    # Main view: Zoomed near z = 1 (Review 2.2)
    ax.plot(
        np.cos(theta_circ),
        np.sin(theta_circ),
        color=COLOR_CRIT,
        linestyle="-",
        linewidth=1.2,
        alpha=0.8,
        label="Unit Circle (|z| = 1)",
    )
    ax.fill(
        np.cos(theta_circ),
        np.sin(theta_circ),
        color=COLOR_TARGET,
        alpha=0.04,
        label="Stable Region (|z| < 1)",
    )

    # Plot SciPy oracle locus if present (dashed green)
    if py_locus:
        py_re = np.array(py_locus["poles_re"])
        py_im = np.array(py_locus["poles_im"])
        py_z = np.exp((py_re + 1j * py_im) * ts)
        for branch in range(py_z.shape[1]):
            ax.plot(
                py_z.real[:, branch],
                py_z.imag[:, branch],
                color=COLOR_GREEN,
                linestyle=(0, (3, 3)),
                linewidth=1.4,
                alpha=0.85,
                label="SciPy Oracle Roots" if branch == 0 else None,
                zorder=4,
            )

    # Plot 4 branches in Z-plane (Rust native)
    for branch in range(4):
        ax.plot(
            z_re[:, branch],
            z_im[:, branch],
            color=COLOR_PRIMARY,
            linewidth=1.6,
            alpha=0.9,
            label="Rust Native Trajectory" if branch == 0 else None,
            zorder=3,
        )

    # Direction arrows at the ends of visible branches (Branches 1, 2, 3)
    for b in [1, 2, 3]:
        pts_disp = ax.transData.transform(np.column_stack([z_re[:, b], z_im[:, b]]))
        tip = pts_disp[-1]
        dists = np.hypot(pts_disp[:, 0] - tip[0], pts_disp[:, 1] - tip[1])
        idx = np.where(dists >= 16.0)[0]
        if len(idx) > 0:
            tail_idx = idx[-1]
            ax.annotate(
                "",
                xy=(z_re[-1, b], z_im[-1, b]),
                xytext=(z_re[tail_idx, b], z_im[tail_idx, b]),
                arrowprops=dict(
                    arrowstyle="-|>",
                    color=COLOR_PRIMARY,
                    lw=1.5,
                    mutation_scale=13,
                ),
                zorder=6,
            )

    # Open loop poles (gain = 0)
    ax.scatter(
        z_re[0, :],
        z_im[0, :],
        color=COLOR_SECONDARY,
        marker="x",
        s=55,
        linewidths=1.8,
        label="Open-Loop Poles (K = 0)",
        zorder=5,
    )

    # Nominal closed-loop poles (at K_nom ~= gains[len/2])
    nom_idx = len(z_re) // 2
    ax.scatter(
        z_re[nom_idx, :],
        z_im[nom_idx, :],
        color=COLOR_TERTIARY,
        marker="d",
        s=60,
        label=r"Nominal $K_{\rm nom}$ Poles",
        zorder=6,
    )

    # Lead compensator zero
    lead = data["analysis"]["lead_design"]
    zero_val = -1.0 / lead["time_constant_t_s"]
    z_zero = np.exp(zero_val * ts)
    ax.scatter(
        [z_zero],
        [0.0],
        color=COLOR_TARGET,
        marker="o",
        facecolors="none",
        edgecolors=COLOR_TARGET,
        s=55,
        linewidths=1.8,
        label=f"Compensator Zero (z = {z_zero:.3f})",
        zorder=5,
    )

    ax.axhline(0, color=COLOR_ASYMPTOTE, linestyle=":", linewidth=0.8, alpha=0.5)

    ax.set_title("Root Locus Pole Trajectories (Z-Plane Zoom Near z = 1)", loc="left", pad=8, fontweight="bold")
    ax.set_xlabel(r"Real Axis $\mathrm{Re}\{z\}$")
    ax.set_ylabel(r"Imaginary Axis $\mathrm{Im}\{z\}$")
    ax.set_xlim(0.85, 1.025)
    ax.set_ylim(-0.048, 0.048)
    ax.legend(loc="lower left", fontsize=7.2)

    # Thumbnail inset: Full unit circle |z| <= 1 overview (Review 2.2)
    ax_ins = ax.inset_axes([0.05, 0.58, 0.30, 0.38])
    ax_ins.set_facecolor(PANEL_BG)
    ax_ins.plot(np.cos(theta_circ), np.sin(theta_circ), color=COLOR_CRIT, linewidth=1.0, alpha=0.7)
    ax_ins.fill(np.cos(theta_circ), np.sin(theta_circ), color=COLOR_TARGET, alpha=0.04)
    if py_locus:
        for branch in range(py_z.shape[1]):
            ax_ins.plot(
                py_z.real[:, branch],
                py_z.imag[:, branch],
                color=COLOR_GREEN,
                linestyle=(0, (2, 2)),
                linewidth=0.8,
                alpha=0.7,
            )
    for branch in range(4):
        ax_ins.plot(z_re[:, branch], z_im[:, branch], color=COLOR_PRIMARY, linewidth=1.0, alpha=0.7)
        pts_ins = ax_ins.transData.transform(np.column_stack([z_re[:, branch], z_im[:, branch]]))
        tip = pts_ins[-1]
        dists = np.hypot(pts_ins[:, 0] - tip[0], pts_ins[:, 1] - tip[1])
        idx = np.where(dists >= 8.0)[0]
        if len(idx) > 0:
            tail_idx = idx[-1]
            ax_ins.annotate(
                "",
                xy=(z_re[-1, branch], z_im[-1, branch]),
                xytext=(z_re[tail_idx, branch], z_im[tail_idx, branch]),
                arrowprops=dict(
                    arrowstyle="-|>",
                    color=COLOR_PRIMARY,
                    lw=1.0,
                    mutation_scale=8,
                ),
            )
    ax_ins.set_xlim(-1.15, 1.15)
    ax_ins.set_ylim(-1.15, 1.15)
    ax_ins.set_aspect("equal")
    ax_ins.set_title("Full |z| ≤ 1 Context", fontsize=7.0, color=TEXT_COLOR, pad=2)
    ax_ins.tick_params(labelsize=5.5, colors=SUBDUED_TEXT)

    # Red bounding box highlighting zoom window
    rect = patches.Rectangle(
        (0.85, -0.048),
        0.175,
        0.096,
        linewidth=1.0,
        edgecolor=COLOR_CRIT,
        facecolor="none",
        linestyle="--",
    )
    ax_ins.add_patch(rect)


def plot_position_tracking(ax, data: dict):
    """Closed-loop position tracking comparing Ideal vs Lead vs PID with 16-bit encoder."""
    ctrl_data = data["controllers"]
    lead_traj = ctrl_data["controller_a_lead"]["trajectory"]
    pid_traj = ctrl_data["controller_b_pid"]["trajectory"]
    ideal_traj = ctrl_data["ideal_baseline"]["trajectory"]

    t = np.array(lead_traj["time"])

    # Reference setpoint & ±2% target band
    ax.axhline(
        1.0,
        color=COLOR_TARGET,
        linestyle="--",
        linewidth=1.0,
        label=r"Setpoint $\theta_{\rm ref}$ (1.0 rad)",
        alpha=0.5
    )
    target_band = 0.02 * 1.0
    ax.axhspan(
        1.0 - target_band,
        1.0 + target_band,
        color=COLOR_TARGET,
        alpha=0.08,
        label=r"$\pm 2\%$ Target Band (0.98–1.02 rad)",
    )

    # Controller A (Primary)
    ax.plot(
        t,
        lead_traj["theta_true"],
        linewidth=1.3,
        label="Controller A: Lead (DirectForm2T)",
    )

    # Controller B (Secondary)
    ax.plot(
        t,
        pid_traj["theta_true"],
        linewidth=1.2,
        label="Controller B: Discrete PID",
    )

    # Ideal Baseline (Stark White)
    ax.plot(
        ideal_traj["time"],
        ideal_traj["theta_true"],
        color=COLOR_WHITE,
        linewidth=1.2,
        alpha=0.65,
        label="Ideal Baseline (No Delay/Noise)",
    )

    # Overlay encoder quantized measurements for Lead (Orange)
    sample_stride = 25
    ax.scatter(
        t[::sample_stride],
        lead_traj["theta_meas"][::sample_stride],
        color=COLOR_ORANGE,
        marker=".",
        s=24,
        alpha=0.6,
        label="16-bit Encoder Measurement",
    )

    # Annotate load disturbance at t = 0.45 s
    dist_t = 0.45
    ax.axvline(dist_t, color=SUBDUED_TEXT, linestyle="--", linewidth=1.0, alpha=0.7)
    ax.text(
        dist_t - 0.015,
        1.28,
        r"Load Disturbance $\tau_L = 0.02\,\mathrm{N\cdot m}$",
        color=SUBDUED_TEXT,
        fontsize=6.5,
        fontweight="bold",
        ha="right",
    )

    lead_m = lead_traj["metrics"]
    pid_m = pid_traj["metrics"]
    summary_text = (
        f"Controller A (Lead DF2T):\n"
        f"  Pre-dist $e_{{ss}}$: {lead_m['steady_state_error_rad'] * 1e3:.1f} mrad\n"
        f"  Dist Dip: {lead_m['disturbance_dip_rad'] * 1e3:.1f} mrad\n"
        f"  Restored $\\theta$: {lead_m['restored_angle_rad']:.3f} rad (Droop)\n"
        f"Controller B (PID):\n"
        f"  Pre-dist $e_{{ss}}$: {pid_m['steady_state_error_rad'] * 1e3:.1f} mrad\n"
        f"  Dist Dip: {pid_m['disturbance_dip_rad'] * 1e3:.1f} mrad\n"
        f"  Restored $\\theta$: {pid_m['restored_angle_rad']:.3f} rad (Integral zero err)"
    )
    # Placed in the lower-right clear space (t in [0.7, 1.2], theta < 0.6) - shifted left 20%
    ax.text(
        0.36,
        0.06,
        summary_text,
        transform=ax.transAxes,
        fontsize=6.0,
        fontfamily="monospace",
        color=TEXT_COLOR,
        bbox=dict(
            boxstyle="round,pad=0.3",
            facecolor=PANEL_BG,
            edgecolor=GRID_COLOR,
            alpha=0.9,
        ),
    )

    ax.set_title(
        "Closed-Loop Position Tracking & Disturbance Rejection",
        loc="left",
        fontweight="bold",
        pad=8,
    )
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Rotor Angle (rad)")
    ax.legend(loc="upper right", fontsize=6.0)
    ax.set_xlim(0.0, 1.2)
    ax.set_ylim(-0.1, 1.45)


def plot_actuator_and_current(ax_u, ax_i, data: dict):
    """Actuator terminal voltage (clamping/noise) and armature current."""
    ctrl_data = data["controllers"]
    lead_traj = ctrl_data["controller_a_lead"]["trajectory"]
    pid_traj = ctrl_data["controller_b_pid"]["trajectory"]
    t = np.array(lead_traj["time"])

    # Terminal Voltage: Lead (Primary), PID (Secondary)
    v_max = data["plant"]["v_max"]
    ax_u.plot(
        t,
        lead_traj["v_applied"],
        linewidth=1.1,
        alpha=0.85,
        label=r"Lead $V_a(t)$ (Noisy/Delayed)",
    )
    ax_u.plot(
        t,
        pid_traj["v_applied"],
        linewidth=1.0,
        alpha=0.8,
        label=r"PID $V_a(t)$",
    )
    ax_u.axhline(
        v_max,
        color=COLOR_CRIT,
        linestyle=":",
        linewidth=0.9,
        alpha=0.7,
        label=f"$\\pm {v_max:.0f}$ V Saturation Limit",
    )
    ax_u.axhline(-v_max, color=COLOR_CRIT, linestyle=":", linewidth=0.9, alpha=0.7)

    # Disturbance marker on voltage axis
    dist_t = 0.45
    ax_u.axvline(dist_t, color=COLOR_CRIT, linestyle="--", linewidth=1.0, alpha=0.6)

    ax_u.set_ylabel("Voltage (V)")
    ax_u.set_title("Control Voltage & Armature Current", loc="left", pad=8, fontweight="bold")
    ax_u.legend(loc="upper right", fontsize=7.5)
    ax_u.set_xlim(0.0, 1.2)
    ax_u.set_ylim(-14.0, 14.0)
    plt.setp(ax_u.get_xticklabels(), visible=False)

    # Armature Current: Lead (Primary), PID (Secondary)
    ax_i.plot(
        t, lead_traj["i_a"], linewidth=1.2, label=r"Lead $i_a(t)$"
    )
    ax_i.plot(
        t,
        pid_traj["i_a"],
        linewidth=1.0,
        label=r"PID $i_a(t)$",
    )
    ax_i.axvline(dist_t, color=COLOR_CRIT, linestyle="--", linewidth=1.0, alpha=0.6)

    # Theoretical steady-state current under load: i_ss = tau_L / K_t
    k_t = data["plant"]["k_t"]
    tau_dist = 0.02
    i_ss = tau_dist / k_t  # 0.40 A
    ax_i.axhline(
        i_ss,
        color=COLOR_TARGET,
        linestyle=":",
        linewidth=1.1,
        alpha=0.85,
        label=rf"Load Demand $i_{{ss}} = \tau_L/K_t = {i_ss:.2f}\,\mathrm{{A}}$",
    )

    ax_i.set_xlabel("Time (s)")
    ax_i.set_ylabel("Current (A)")
    ax_i.legend(loc="upper right", fontsize=7.5)
    ax_i.set_xlim(0.0, 1.2)


def main():
    default_h5 = Path(__file__).resolve().parent.parent / "results" / "dc-motor.rust.h5"
    default_output = (
            Path(__file__).resolve().parent.parent / "results" / "dc_motor_validation.png"
    )

    parser = setup_argument_parser(
        description="Render DC motor classical control dashboard.",
        default_json=default_h5,
        default_output=default_output,
    )
    args = parser.parse_args()

    apply_theme(font_size=10)

    json_path = resolve_results_path(
        args.results,
        [
            default_h5,
            Path("results/dc-motor.rust.h5"),
            Path("control-rs-validation/results/dc-motor.rust.h5"),
        ],
        error_msg="Could not locate 'results/dc-motor.rust.h5'. Run 'cargo run' first.",
    )
    print(f"Loading validation results from: {json_path}")
    data = load_plot_container(json_path)
    py_locus = (
        data.get("oracle", {}).get("analysis", {}).get("root_locus")
        or data.get("oracle", {}).get("root_locus")
    )

    # Figure Setup: 2x2 Dashboard
    fig = plt.figure(figsize=(16, 10), facecolor=BG_COLOR)
    gs = fig.add_gridspec(2, 2, hspace=0.32, wspace=0.25)

    # Bode (split into 2 sub-axes)
    gs_a = gs[0, 0].subgridspec(2, 1, height_ratios=[1, 1], hspace=0.15)
    ax_mag = fig.add_subplot(gs_a[0, 0])
    ax_phase = fig.add_subplot(gs_a[1, 0], sharex=ax_mag)
    plot_frequency_response(ax_mag, ax_phase, data)

    # Root Locus (Z-Plane)
    ax_rl = fig.add_subplot(gs[0, 1])
    plot_root_locus(ax_rl, data, py_locus=py_locus)

    # Position Tracking
    ax_pos = fig.add_subplot(gs[1, 0])
    plot_position_tracking(ax_pos, data)

    # Actuator Voltage & Current
    gs_d = gs[1, 1].subgridspec(2, 1, height_ratios=[1, 1], hspace=0.2)
    ax_u = fig.add_subplot(gs_d[0, 0])
    ax_i = fig.add_subplot(gs_d[1, 0], sharex=ax_u)
    plot_actuator_and_current(ax_u, ax_i, data)

    fig.suptitle(
        "control-rs — DC Motor Classical Control Validation & Closed-Loop Simulation",
        fontsize=15,
        fontweight="bold",
        color=TEXT_COLOR,
        y=0.98,
    )

    output_path = default_output if not args.output else args.output
    save_or_show(fig, output_path, show=args.show, dpi=200)


if __name__ == "__main__":
    main()
