#!/usr/bin/env python3
"""
plot_buck_converter.py

Visualizer for the buck converter classical control validation results
(documentation/control-toolboxes/classical-tools-design.md, §6.6).

Loads `results/buck-converter.*.h5` generated by `cargo run --bin validate`
and renders a 4-panel dark-themed dashboard:
  1. Frequency Response (Bode magnitude & phase, crossover & phase margin)
  2. Root Locus Trajectory (s-plane pole migration across loop gain sweep)
  3. Closed-Loop Transient Step Response (Linear ZOH vs Nonlinear CCM circuit)
  4. Load Disturbance Rejection (50% load drop transient recovery)

Usage:
  python3 plot_buck_converter.py [--show] [--json <path>] [--output <path>]
"""

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# Ensure shared python3 directory is on sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent))

from control_rs_plot import (
    BG_COLOR,
    COLOR_AMBER,
    COLOR_ASYMPTOTE,
    COLOR_CRIT,
    COLOR_PRIMARY,
    COLOR_QUATERNARY,
    COLOR_SECONDARY,
    COLOR_TARGET,
    COLOR_TERTIARY,
    COLOR_WHITE,
    GRID_COLOR,
    PANEL_BG,
    SUBDUED_TEXT,
    TEXT_COLOR,
    apply_theme,
    resolve_results_path,
    save_or_show,
    setup_argument_parser,
    load_plot_container,
)


def plot_frequency_response(ax_mag, ax_phase, data: dict) -> None:
    """Bode plot showing plant, compensator, open-loop gain and phase margins."""
    freqs_khz = np.array(data["frequency_sweep"]["omegas"]) / (2.0 * np.pi * 1e3)
    uncomp_mag = np.array(data["frequency_sweep"]["uncomp_mag_db"])
    comp_mag = np.array(data["frequency_sweep"]["comp_mag_db"])
    uncomp_phase = np.array(data["frequency_sweep"]["uncomp_phase_deg"])
    comp_phase = np.array(data["frequency_sweep"]["comp_phase_deg"])

    wc_comp_khz = (
        data["margins"]["compensated"]["gain_crossover_rad_s"] / (2.0 * np.pi * 1e3)
        if data["margins"]["compensated"]["gain_crossover_rad_s"]
        else None
    )
    pm_comp_deg = data["margins"]["compensated"]["phase_margin_deg"]

    # Magnitude: loop first (Primary), plant second (Secondary)
    ax_mag.semilogx(freqs_khz, comp_mag, label="Loop L(s) = C(s)·G_vd(s)")
    ax_mag.semilogx(freqs_khz, uncomp_mag, label="Plant G_vd(s)")
    ax_mag.axhline(0.0, color=COLOR_ASYMPTOTE, linestyle=":", linewidth=0.9, alpha=0.5, label="0 dB Crossover")
    if wc_comp_khz:
        ax_mag.axvline(wc_comp_khz, color=COLOR_PRIMARY, linestyle=":", linewidth=1.1, alpha=0.7)

    if "oracle" in data and data["oracle"].get("ngspice"):
        ng_ac = data["oracle"]["ngspice"]["ac_sweep"]
        f_ng_khz = np.array(ng_ac["freq_hz"]) / 1e3
        m_ng = np.array(ng_ac["mag_db"])
        ax_mag.plot(
            f_ng_khz[::10],
            m_ng[::10],
            "--",
            color=COLOR_TERTIARY,
            linewidth=1.2,
            markersize=3.0,
            alpha=0.7,
            label="ngspice AC Plant",
        )

    gm_val = data["margins"]["compensated"].get("gain_margin_db")
    gm_str = f"GM: {gm_val:.1f} dB" if gm_val is not None else "GM: unbounded (no −180° crossing)"
    ax_mag.text(
        0.98,
        0.90,
        gm_str,
        transform=ax_mag.transAxes,
        fontsize=8.0,
        fontweight="bold",
        horizontalalignment="right",
        color=TEXT_COLOR,
        bbox=dict(
            boxstyle="round,pad=0.3",
            facecolor=PANEL_BG,
            edgecolor=GRID_COLOR,
            alpha=0.9,
        ),
    )

    ax_mag.set_ylabel("Magnitude (dB)", fontweight="bold")
    ax_mag.set_title("Frequency Response & Stability Margins (Bode)", loc="left", pad=8, fontweight="bold")
    ax_mag.legend(loc="lower left", fontsize=8.0)
    plt.setp(ax_mag.get_xticklabels(), visible=False)

    # Phase: loop first (Primary), plant second (Secondary)
    ax_phase.semilogx(freqs_khz, comp_phase, label="Compensated Phase")
    ax_phase.semilogx(freqs_khz, uncomp_phase, label="Plant Phase")
    ax_phase.axhline(-180.0, color=COLOR_CRIT, linestyle=":", linewidth=0.9, alpha=0.7, label="-180° Critical")
    if wc_comp_khz and pm_comp_deg:
        ax_phase.axvline(wc_comp_khz, color=COLOR_PRIMARY, linestyle=":", linewidth=1.1, alpha=0.7)
        ax_phase.annotate(
            f"Phase Margin: {pm_comp_deg:.1f}°\n(Target: ≥ 45°)",
            xy=(wc_comp_khz, -180.0 + pm_comp_deg),
            xytext=(wc_comp_khz * 3.2, -55.0),
            arrowprops=dict(arrowstyle="->", color=COLOR_TARGET, lw=1.2, shrinkB=4),
            color=TEXT_COLOR,
            fontweight="bold",
            fontsize=8.0,
            bbox=dict(boxstyle="round,pad=0.3", facecolor=PANEL_BG, edgecolor=GRID_COLOR, alpha=0.9),
        )
    ax_phase.set_xlabel("Frequency (kHz)", fontweight="bold")
    ax_phase.set_ylabel("Phase (deg)", fontweight="bold")
    ax_phase.set_ylim(-195, 10)
    ax_phase.legend(loc="lower left", fontsize=8.0)


def plot_root_locus(ax, data: dict) -> None:
    """Root locus trajectory showing closed-loop pole migration across loop gain sweep."""
    gains = np.array(data["root_locus"]["gains"])
    poles_re = np.array(data["root_locus"]["poles_re"]) / 1e3
    poles_im = np.array(data["root_locus"]["poles_im"]) / 1e3

    ax.axvspan(-70, 0, color=COLOR_TARGET, alpha=0.04, label="Stable Region (Re{s} < 0)")
    ax.axvline(0, color=COLOR_CRIT, linestyle="-", linewidth=1.2, alpha=0.7)
    ax.axhline(0, color=COLOR_ASYMPTOTE, linestyle="--", linewidth=0.8, alpha=0.5)

    for branch in range(3):
        ax.plot(
            poles_re[:, branch],
            poles_im[:, branch],
            color=COLOR_PRIMARY,
            linewidth=1.3,
            alpha=0.85,
        )

    # Direction arrows at the ends of all 3 branches
    for b in range(3):
        pts_disp = ax.transData.transform(np.column_stack([poles_re[:, b], poles_im[:, b]]))
        tip = pts_disp[-1]
        dists = np.hypot(pts_disp[:, 0] - tip[0], pts_disp[:, 1] - tip[1])
        idx = np.where(dists >= 16.0)[0]
        if len(idx) > 0:
            tail_idx = idx[-1]
            ax.annotate(
                "",
                xy=(poles_re[-1, b], poles_im[-1, b]),
                xytext=(poles_re[tail_idx, b], poles_im[tail_idx, b]),
                arrowprops=dict(
                    arrowstyle="-|>",
                    color=COLOR_PRIMARY,
                    lw=1.5,
                    mutation_scale=13,
                ),
                zorder=6,
            )

    ax.plot(
        poles_re[0, :],
        poles_im[0, :],
        "x",
        color=COLOR_SECONDARY,
        markersize=8,
        markeredgewidth=1.8,
        label="Open-Loop Poles (K = 0)",
    )

    zero_re = -data["compensator"]["zero_rad_s"] / 1e3
    ax.plot(
        [zero_re],
        [0.0],
        "o",
        color=COLOR_TARGET,
        markersize=8,
        markeredgewidth=1.6,
        fillstyle="none",
        label=f"Compensator Zero ({zero_re:.1f} krad/s)",
    )

    nom_idx = len(gains) // 2
    ax.plot(
        poles_re[nom_idx, :],
        poles_im[nom_idx, :],
        "d",
        color=COLOR_TERTIARY,
        markersize=7,
        label=f"Nominal Operating Poles (K = {gains[nom_idx]:.2f})",
    )

    ax.set_title("Root Locus Closed-Loop Pole Migration (0 ≤ K ≤ 2·K_nom)", loc="left", pad=8, fontweight="bold")
    ax.set_xlabel("Real Axis σ (krad/s)", fontweight="bold")
    ax.set_ylabel("Imaginary Axis jω (krad/s)", fontweight="bold")
    ax.set_xlim(-65, 5)
    ax.set_ylim(-55, 55)
    ax.legend(loc="lower left", fontsize=8.0)


def plot_step_response(ax, data: dict) -> None:
    """Closed-loop setpoint step response comparing linear sampled-data vs nonlinear models."""
    t_lin_ms = np.array(data["simulation"]["linear_step"]["time_s"]) * 1e3
    vo_lin = np.array(data["simulation"]["linear_step"]["v_out_v"])
    t_nonlin_ms = np.array(data["simulation"]["nonlinear_step"]["time_s"]) * 1e3
    vo_nonlin = np.array(data["simulation"]["nonlinear_step"]["v_out_v"])

    ax.plot(
        t_lin_ms,
        vo_lin,
        "o",
        label="Linear Sampled-Data (ZOH + DF2T)",
        markersize=2.2,
        alpha=0.85,
    )
    ax.plot(
        t_nonlin_ms,
        vo_nonlin,
        label="Nonlinear Averaged Circuit (RK4)",
        linewidth=1.3,
        alpha=0.9,
    )

    if "oracle" in data and data["oracle"].get("ngspice"):
        ng = data["oracle"]["ngspice"]
        if "averaged_step" in ng:
            t_ng_ms = np.array(ng["averaged_step"]["time_s"]) * 1e3
            vo_ng = np.array(ng["averaged_step"]["v_out_v"])
            ax.plot(
                t_ng_ms,
                vo_ng,
                label="ngspice Averaged Model",
                linewidth=1.2,
                linestyle="-.",
                alpha=0.85,
            )
        if "switched_step" in ng:
            t_sw_ms = np.array(ng["switched_step"]["time_s"]) * 1e3
            vo_sw = np.array(ng["switched_step"]["v_out_v"])
            ax.plot(
                t_sw_ms,
                vo_sw,
                label="ngspice Switched PWM (100 kHz)",
                linewidth=0.8,
                alpha=0.55,
            )

    ax.axhline(5.5, color=COLOR_TARGET, linestyle=":", linewidth=1.0, alpha=0.7, label="Target (5.5 V)")

    target_band = 0.02 * 0.5
    ax.axhspan(
        5.5 - target_band,
        5.5 + target_band,
        color=COLOR_TARGET,
        alpha=0.08,
        label="±2% Target Band (5.49–5.51 V)",
    )

    v_final = vo_lin[-1]
    ax.plot(
        [0.0, 3.0],
        [v_final, v_final],
        "--",
        color=COLOR_ASYMPTOTE,
        linewidth=0.8,
        alpha=0.7,
        label=f"Achieved Final ({v_final:.3f} V)",
    )

    ax.set_title("Closed-Loop Setpoint Step Response (+0.5 V at t = 0.5 ms)", loc="left", pad=8, fontweight="bold")
    ax.set_xlabel("Time (ms)", fontweight="bold")
    ax.set_ylabel("Output Voltage V_o (V)", fontweight="bold")
    ax.set_ylim(4.9, 5.7)

    m_lin = data["simulation"]["linear_step"]["metrics"]
    ts_target = m_lin.get("settling_time_target_us")
    ts_target_str = f"{ts_target:.1f} μs" if ts_target is not None else "unsettled (Type-0 e_ss > 2%)"

    ts_final = m_lin.get("settling_time_final_us")
    if ts_final is None:
        ts_final = m_lin.get("settling_time_us", 0.0)

    metrics_text = (
        f"Rise Time (t_r): {m_lin['rise_time_us']:.1f} μs\n"
        f"Overshoot (M_p): {m_lin['peak_overshoot_pct']:.1f}%\n"
        f"Settling (±2% target): {ts_target_str}\n"
        f"Settling (±2% final): {ts_final:.1f} μs\n"
        f"Steady-State Error: {m_lin['steady_state_error_v'] * 1e3:.1f} mV\n"
        f"Theoretical e_ss: Δv/(1+K·α·Vin) = 90.9 mV"
    )
    ax.text(
        0.58,
        0.14,
        metrics_text,
        transform=ax.transAxes,
        fontsize=8.0,
        verticalalignment="bottom",
        bbox=dict(
            boxstyle="round,pad=0.4",
            facecolor=PANEL_BG,
            edgecolor=GRID_COLOR,
            alpha=0.95,
        ),
        color=TEXT_COLOR,
    )
    ax.legend(loc="upper right", bbox_to_anchor=(0.90, 1.0), fontsize=8.0)


def plot_load_transient(ax_v, ax_i, data: dict) -> None:
    """Load disturbance rejection showing output voltage dip/recovery and inductor current."""
    load_key = "load_transient" if "load_transient" in data["simulation"] else "load_disturbance"
    t_load_ms = np.array(data["simulation"][load_key]["time_s"]) * 1e3
    vo_load = np.array(data["simulation"][load_key]["v_out_v"])
    il_load = np.array(data["simulation"][load_key]["i_l_a"])

    # Output Voltage (ax_v)
    ax_v.plot(t_load_ms, vo_load, linewidth=1.3, label="Output Voltage V_o(t)")

    if "oracle" in data and data["oracle"].get("ngspice"):
        ng = data["oracle"]["ngspice"]
        if "averaged_load" in ng:
            t_ng_l_ms = np.array(ng["averaged_load"]["time_s"]) * 1e3
            vo_ng_l = np.array(ng["averaged_load"]["v_out_v"])
            ax_v.plot(
                t_ng_l_ms,
                vo_ng_l,
                label="ngspice Averaged Model",
                linewidth=1.2,
                linestyle="-.",
                alpha=0.85,
            )

    ax_v.axhline(5.0, color=COLOR_TARGET, linestyle=":", linewidth=1.0, alpha=0.6, label="Target (5.0 V)")
    ax_v.axvline(1.0, color=COLOR_CRIT, linestyle="--", linewidth=1.2, alpha=0.8, label="Load Step (5 A → 2.5 A)")

    load_metrics = data["simulation"][load_key]
    peak_spike = load_metrics["peak_v"]
    rec_time_us = load_metrics.get(
        "recovery_time_us",
        load_metrics.get("recovery_time_s", 0.0) * 1e6,
    )

    ax_v.annotate(
        f"Peak Spike: {peak_spike:.3f} V\n(+{(peak_spike - 5.0) * 1e3:.0f} mV spike)\nRecovery: {rec_time_us:.1f} μs (±1%)",
        xy=(1.06, peak_spike),
        xytext=(1.45, 5.50),
        arrowprops=dict(arrowstyle="->", color=COLOR_PRIMARY, lw=1.2),
        color=TEXT_COLOR,
        fontweight="bold",
        fontsize=8.0,
        bbox=dict(boxstyle="round,pad=0.3", facecolor=PANEL_BG, edgecolor=GRID_COLOR, alpha=0.9),
    )

    ax_v.text(
        0.03,
        0.08,
        "Type-0 CCM Equilibrium:\nV_o = D_0 · V_in = (5/12) · 12 V = 5.0 V\n(Equilibrium is load-independent in lossless CCM)",
        transform=ax_v.transAxes,
        fontsize=7.5,
        verticalalignment="bottom",
        bbox=dict(
            boxstyle="round,pad=0.3",
            facecolor=PANEL_BG,
            edgecolor=GRID_COLOR,
            alpha=0.9,
        ),
        color=TEXT_COLOR,
    )

    ax_v.set_ylabel("Voltage V_o (V)", fontweight="bold")
    ax_v.set_ylim(4.7, 5.9)
    ax_v.set_title("Load Transient Response (50% Load Drop: 1.0 Ω → 2.0 Ω at t = 1.0 ms)", loc="left", pad=8,
                   fontweight="bold")
    ax_v.legend(loc="upper right", fontsize=7.5)
    plt.setp(ax_v.get_xticklabels(), visible=False)

    # Inductor Current (ax_i)
    ax_i.plot(t_load_ms, il_load, linewidth=1.2, label="Inductor Current i_L(t)")
    ax_i.axvline(1.0, color=COLOR_CRIT, linestyle="--", linewidth=1.0, alpha=0.8)
    ax_i.axhline(2.5, color=COLOR_TARGET, linestyle=":", linewidth=1.1, alpha=0.85,
                 label=r"Post-Step Steady State ($I_o = 2.5$ A)")

    ax_i.set_xlabel("Time (ms)", fontweight="bold")
    ax_i.set_ylabel("Current i_L (A)", fontweight="bold")
    ax_i.set_ylim(0.8, 5.6)
    ax_i.legend(loc="upper right", fontsize=7.5)


def main():
    default_h5 = Path(__file__).resolve().parent.parent / "results/buck-converter.rust.h5"
    default_output = Path(__file__).resolve().parent.parent / "results/buck_converter_validation.png"

    parser = setup_argument_parser(
        description="Plot buck converter validation results.",
        default_json=default_h5,
        default_output=default_output,
    )
    args = parser.parse_args()

    apply_theme(font_size=10)

    json_path = resolve_results_path(
        args.results,
        [
            default_h5,
            Path("results/buck-converter.rust.h5"),
            Path("control-rs-validation/results/buck-converter.rust.h5"),
        ],
        error_msg="Could not locate 'results/buck-converter.rust.h5'. Run 'cargo run' first.",
    )
    print(f"Loading validation results from: {json_path}")
    data = load_plot_container(json_path)

    fig = plt.figure(figsize=(18, 11), facecolor=BG_COLOR)
    fig.suptitle(
        "control-rs — Buck Converter Classical Control Validation & Closed-Loop Simulation",
        fontsize=15,
        fontweight="bold",
        color=TEXT_COLOR,
        y=0.98,
    )

    gs = fig.add_gridspec(2, 2, hspace=0.32, wspace=0.25)

    # Panel 1: Frequency Response (Bode)
    gs_bode = gs[0, 0].subgridspec(2, 1, hspace=0.10, height_ratios=[1.2, 1.0])
    ax_mag = fig.add_subplot(gs_bode[0, 0])
    ax_phase = fig.add_subplot(gs_bode[1, 0], sharex=ax_mag)
    plot_frequency_response(ax_mag, ax_phase, data)

    # Panel 2: Root Locus
    ax_locus = fig.add_subplot(gs[0, 1])
    plot_root_locus(ax_locus, data)

    # Panel 3: Step Response
    ax_step = fig.add_subplot(gs[1, 0])
    plot_step_response(ax_step, data)

    # Panel 4: Load Transient (2x1 Subgrid)
    gs_load = gs[1, 1].subgridspec(2, 1, hspace=0.20, height_ratios=[1.0, 1.0])
    ax_v = fig.add_subplot(gs_load[0, 0])
    ax_i = fig.add_subplot(gs_load[1, 0], sharex=ax_v)
    plot_load_transient(ax_v, ax_i, data)

    save_or_show(
        fig,
        default_output if not args.output else args.output,
        show=args.show,
        dpi=200,
    )


if __name__ == "__main__":
    main()
