[package]
name = "control-rs-xtask"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.0", features = ["alloc"] }
ratatui = "0.26"
crossterm = "0.27"
control-rs-hil = { path = "../control-rs-hil" }
serialport = "4.3"
toml = "0.8"
