[package]
name = "control-rs-xtask"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.0", features = ["alloc"] }
ratatui = "0.30"
crossterm = "0.29"
control-rs-ets = { path = "../control-rs-ets" }
serde_json = "1.0"
serial2 = "0.2.37"
crc = "3.4.0"