//! Multi-target runner: cargo bin, external commands, then true-oracle HDF5 compare.

use std::env;
use std::fmt::Write as _;
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::{Duration, Instant, SystemTime};

use super::envelope::{ContainerValidationReport, FreshnessPolicy};
use super::h5::validate_suite_files;

/// One subprocess argv (program plus arguments).
pub type CommandArgv = Vec<String>;

/// External variant subprocesses for a suite.
pub type CommandList = Vec<CommandArgv>;

/// Outcome of running a single example validation crate.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ExampleRunOutcome {
    /// Crate name or short identifier.
    pub name: String,
    /// Path relative to repo root.
    pub path: String,
    /// Whether every configured command succeeded and envelopes are valid.
    pub success: bool,
    /// Captured stdout and stderr.
    pub output: String,
    /// Execution duration in seconds.
    pub duration_secs: f32,
    /// Validated result envelopes generated by the run.
    pub envelopes: Vec<ContainerValidationReport>,
    /// Provenance of comparison bounds.
    #[serde(default)]
    pub tolerance_source: String,
    /// Number of comparison records produced.
    #[serde(default)]
    pub tolerance_keys: usize,
}

/// Configuration for an example cross-comparison target.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExampleTargetConfig {
    /// Suite id and HDF5 glob stem (`results/<name>.<variant>.h5`).
    pub name: String,
    /// Working directory / crate path for this suite's cargo bin.
    #[serde(alias = "path", alias = "dir", default = "default_manifest_path")]
    pub manifest_path: String,
    /// Local implementation binary. The runner invokes `cargo run --release --bin <bin>`.
    pub bin: String,
    /// True-oracle variant name (`results/<name>.<oracle>.h5`).
    pub oracle: String,
    /// External variant subprocesses. Cargo is not listed here.
    #[serde(default)]
    pub commands: CommandList,
    /// Wall-clock bound for this example, overriding `[ci] timeout_secs`.
    #[serde(default)]
    pub timeout_secs: Option<u64>,
}

struct OutcomeParts {
    name: String,
    path: String,
    success: bool,
    output: String,
    duration_secs: f32,
    envelopes: Vec<ContainerValidationReport>,
}

struct ReportInputs<'a> {
    target: &'a ExampleTargetConfig,
    example_dir: &'a Path,
    name: &'a str,
    field_errs: &'a [String],
    freshness: &'a FreshnessPolicy,
}

fn append_labeled_output(combined: &mut String, label: &str, cmd_out: &str) {
    let _ = write!(combined, "$ {label}\n{cmd_out}\n");
}

fn collect_suite_reports(
    inputs: &ReportInputs<'_>,
    success: &mut bool,
) -> Vec<ContainerValidationReport> {
    let mut envelope_reports = Vec::new();
    if inputs.field_errs.is_empty() && *success {
        let report = validate_suite_files(
            inputs.example_dir,
            &inputs.target.name,
            &inputs.target.oracle,
            Some(inputs.freshness),
        );
        if !report.is_valid {
            *success = false;
        }
        envelope_reports.push(report);
    } else if inputs.field_errs.is_empty() {
        envelope_reports.push(ContainerValidationReport {
            file_path: inputs.example_dir.display().to_string(),
            subject: inputs.name.to_string(),
            sources: Vec::new(),
            comparisons: Vec::new(),
            is_valid: false,
            errors: vec![
                "suite commands failed; HDF5 comparison skipped".to_string(),
            ],
        });
    } else {
        envelope_reports.push(ContainerValidationReport {
            file_path: inputs.example_dir.display().to_string(),
            subject: inputs.name.to_string(),
            sources: Vec::new(),
            comparisons: Vec::new(),
            is_valid: false,
            errors: inputs.field_errs.to_vec(),
        });
    }
    envelope_reports
}

fn default_manifest_path() -> String {
    ".".to_string()
}

fn finish_outcome(
    mut parts: OutcomeParts,
    target: &ExampleTargetConfig,
) -> ExampleRunOutcome {
    let tolerance_keys =
        parts.envelopes.first().map_or(0, |r| r.comparisons.len());
    let tolerance_source = format!(
        "HDF5 attributes on results/{}.{}.h5",
        target.name, target.oracle
    );
    if !parts.success && parts.output.is_empty() {
        parts.output = "suite failed".to_string();
    }
    ExampleRunOutcome {
        name: parts.name,
        path: parts.path,
        success: parts.success,
        output: parts.output,
        duration_secs: parts.duration_secs,
        envelopes: parts.envelopes,
        tolerance_source,
        tolerance_keys,
    }
}

/// Short SHA of the revision under test, when the tree is a git checkout.
fn head_commit(repo_root: &Path) -> Option<String> {
    env::var("GIT_COMMIT").ok().or_else(|| {
        Command::new("git")
            .args(["rev-parse", "--short", "HEAD"])
            .current_dir(repo_root)
            .output()
            .ok()
            .filter(|out| out.status.success())
            .and_then(|out| String::from_utf8(out.stdout).ok())
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
    })
}

/// Kill `pid` and, on Unix, its process group started with `process_group(0)`.
fn kill_process_group(pid: u32) {
    #[cfg(unix)]
    {
        let group_spec = format!("-{pid}");
        let _ = Command::new("kill").args(["-KILL", &group_spec]).status();
    }
    #[cfg(not(unix))]
    {
        let _ = Command::new("taskkill")
            .args(["/F", "/T", "/PID", &pid.to_string()])
            .status();
    }
}

fn resolve_example_dir(example_path: &Path) -> &Path {
    if example_path.is_file()
        || example_path.file_name().is_some_and(|n| n == "Cargo.toml")
    {
        example_path.parent().unwrap_or_else(|| Path::new("."))
    } else {
        example_path
    }
}

/// Run one argv in `cwd` with a wall-clock timeout.
fn run_argv(argv: &[String], cwd: &Path, timeout: Duration) -> (bool, String) {
    let Some((prog, argv_rest)) = argv.split_first() else {
        return (false, "empty command".to_string());
    };
    let label = argv.join(" ");
    let mut cmd = Command::new(prog);
    cmd.args(argv_rest);
    cmd.current_dir(cwd);
    crate::gates::apply_cargo_term_color(&mut cmd);

    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        cmd.process_group(0);
    }

    let mut child =
        match cmd.stdout(Stdio::piped()).stderr(Stdio::piped()).spawn() {
            Ok(c) => c,
            Err(e) => {
                return (false, format!("Failed to spawn `{label}`: {e}"));
            }
        };

    let child_pid = child.id();
    let tee = crate::gates::StdioTee::attach(&mut child);
    let (tx, rx) = std::sync::mpsc::channel();
    let wait_thread = std::thread::spawn(move || {
        let res = child.wait();
        let _ = tx.send(res);
    });

    match rx.recv_timeout(timeout) {
        Ok(Ok(status)) => {
            let _ = wait_thread.join();
            (status.success(), tee.join())
        }
        Ok(Err(e)) => {
            let _ = wait_thread.join();
            let _ = tee.join();
            (false, format!("Failed while waiting for `{label}`: {e}"))
        }
        Err(_) => {
            kill_process_group(child_pid);
            let _ = wait_thread.join();
            let _ = tee.join();
            (
                false,
                format!(
                    "`{label}` timed out after {} seconds",
                    timeout.as_secs()
                ),
            )
        }
    }
}

/// Execute a suite's cargo bin and external commands, then compare globbed HDF5.
#[must_use]
pub fn run_example(
    target: &ExampleTargetConfig,
    repo_root: &Path,
    default_timeout_secs: u64,
) -> ExampleRunOutcome {
    let example_dir = resolve_example_dir(Path::new(&target.manifest_path));
    let rel_path = example_dir
        .strip_prefix(repo_root)
        .unwrap_or(example_dir)
        .to_string_lossy()
        .to_string();
    let name = target.name.clone();
    let start = Instant::now();
    let timeout_duration = Duration::from_secs(
        target.timeout_secs.unwrap_or(default_timeout_secs),
    );
    let field_errs = suite_field_errors(target);
    // Floor is the start of this suite, not the end. Capturing after
    // `run_suite_commands` treats files written before a slow trailing
    // subprocess as stale.
    let freshness = suite_freshness(repo_root);
    let (mut success, output) = if field_errs.is_empty() {
        run_suite_commands(target, example_dir, timeout_duration)
    } else {
        (false, field_errs.join("\n"))
    };
    let envelopes = collect_suite_reports(
        &ReportInputs {
            target,
            example_dir,
            name: &name,
            field_errs: &field_errs,
            freshness: &freshness,
        },
        &mut success,
    );
    finish_outcome(
        OutcomeParts {
            name,
            path: rel_path,
            success,
            output,
            duration_secs: start.elapsed().as_secs_f32(),
            envelopes,
        },
        target,
    )
}

/// Execute multiple example crates sequentially and aggregate their outcomes.
#[must_use]
pub fn run_multiple_examples(
    examples: &[ExampleTargetConfig],
    repo_root: &Path,
    default_timeout_secs: u64,
) -> Vec<ExampleRunOutcome> {
    let mut results = Vec::new();
    for ex in examples {
        results.push(run_example(ex, repo_root, default_timeout_secs));
    }
    results
}

fn run_suite_commands(
    target: &ExampleTargetConfig,
    example_dir: &Path,
    timeout_duration: Duration,
) -> (bool, String) {
    let mut combined = String::new();
    let cargo = vec![
        "cargo".to_string(),
        "run".to_string(),
        "--release".to_string(),
        "--bin".to_string(),
        target.bin.clone(),
    ];
    let label = cargo.join(" ");
    let (cmd_ok, cmd_out) = run_argv(&cargo, example_dir, timeout_duration);
    append_labeled_output(&mut combined, &label, &cmd_out);
    if !cmd_ok {
        return (false, combined);
    }
    for argv in &target.commands {
        let cmd_label = argv.join(" ");
        let (next_ok, next_out) = run_argv(argv, example_dir, timeout_duration);
        append_labeled_output(&mut combined, &cmd_label, &next_out);
        if !next_ok {
            return (false, combined);
        }
    }
    (true, combined)
}

fn suite_freshness(repo_root: &Path) -> FreshnessPolicy {
    let written_after = SystemTime::now()
        .checked_sub(Duration::from_secs(1))
        .unwrap_or_else(SystemTime::now);
    FreshnessPolicy {
        head_commit: head_commit(repo_root),
        written_after: Some(written_after),
    }
}

fn suite_field_errors(target: &ExampleTargetConfig) -> Vec<String> {
    let mut errs = Vec::new();
    if target.name.is_empty() || target.name.contains('.') {
        errs.push(
            "suite `name` is required and must not contain '.'".to_string(),
        );
    }
    if target.bin.is_empty() {
        errs.push("suite `bin` is required".to_string());
    }
    if target.oracle.is_empty() || target.oracle.contains('.') {
        errs.push(
            "suite `oracle` is required and must not contain '.'".to_string(),
        );
    }
    errs
}
