[package]
name = "qemu-example"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = { version = "1.0", default-features = false }
control-rs = { path = "../..", default-features = false, features = ["hil"] }
control-rs-hil = { path = "../../control-rs-hil" }
control-rs-macros = { path = "../../control-rs-macros" }

[[bin]]
name = "control-rs-qemu-arm"
path = "src/main.rs"
test = false

[workspace]

[profile.qemu]
inherits = "release"
strip = false
opt-level = 0
lto = false

[profile.qemu.build-override]
opt-level = 0
