[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"

rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Thil_suites.x",
]

[alias]
build-qemu = "build --profile release-qemu"
run-qemu = "run --profile release-qemu"
check-qemu = "check --profile release-qemu"