#!/usr/bin/env python3
"""Emit SciPy/NumPy equivalence tables as Rust const sources."""

from __future__ import annotations

import argparse
import importlib.util
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
SLUGS = (
    ("matrix", "matrix_prototype.py", "matrix_equiv.rs"),
    ("polynomial", "polynomial_prototype.py", "polynomial_equiv.rs"),
    ("state-space", "state_space_prototype.py", "state_space_equiv.rs"),
    (
        "transfer-function",
        "transfer_function_prototype.py",
        "transfer_function_equiv.rs",
    ),
    ("tensor", "tensor_prototype.py", "tensor_equiv.rs"),
)


def _load(slug: str, filename: str):
    path = ROOT / slug / filename
    spec = importlib.util.spec_from_file_location(f"{slug}_proto", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _rust_scalar(value: float | int, ty: str) -> str:
    if ty == "i32":
        return str(int(value))
    x = float(value)
    if math.isnan(x):
        return f"{ty}::NAN"
    if math.isinf(x):
        sign = "-" if x < 0 else ""
        return f"{sign}{ty}::INFINITY"
    text = format(x, ".17g")
    if ty == "f32":
        if "e" in text or "E" in text or "." in text:
            return text + "_f32"
        return text + ".0_f32"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text


def _emit_const(name: str, value: object) -> list[str]:
    arr = np.asarray(value)
    if arr.dtype.kind in "iu":
        ty = "i32"
    elif arr.dtype == np.float32:
        ty = "f32"
    else:
        ty = "f64"
        arr = arr.astype(np.float64, copy=False)

    if arr.ndim == 0:
        return [f"pub const {name}: {ty} = {_rust_scalar(arr.item(), ty)};"]
    if arr.ndim == 1:
        inner = ", ".join(_rust_scalar(v, ty) for v in arr.tolist())
        return [f"pub const {name}: [{ty}; {arr.size}] = [{inner}];"]
    if arr.ndim == 2:
        rows, cols = arr.shape
        row_txt = []
        for row in arr.tolist():
            inner = ", ".join(_rust_scalar(v, ty) for v in row)
            row_txt.append(f"    [{inner}]")
        body = ",\n".join(row_txt)
        return [
            f"pub const {name}: [[{ty}; {cols}]; {rows}] = [",
            body,
            "];",
        ]
    raise TypeError(f"{name}: unsupported ndim {arr.ndim}")


def _versions() -> tuple[str, str, str]:
    import numpy
    import scipy

    py = sys.version.split()[0]
    return py, numpy.__version__, scipy.__version__


def _write_f64_le(path: Path, arr: np.ndarray) -> None:
    path.write_bytes(np.ascontiguousarray(arr, dtype="<f8").tobytes())


def _write_f32_le(path: Path, arr: np.ndarray) -> None:
    path.write_bytes(np.ascontiguousarray(arr, dtype="<f4").tobytes())


def _well_conditioned(n: int, scale: float) -> np.ndarray:
    idx = np.arange(n, dtype=np.float64)
    return np.eye(n) + scale / (idx[:, None] + idx[None, :] + 1.0)


def _eval_kappa(coeffs: np.ndarray, x: float) -> float:
    """Coefficient-to-value condition number at a real point (Higham Ch. 5)."""
    ax = abs(x)
    tilde = float(np.polynomial.polynomial.polyval(ax, np.abs(coeffs)))
    val = abs(float(np.polynomial.polynomial.polyval(x, coeffs)))
    if val == 0.0:
        return float("inf")
    return tilde / val


def emit(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    py, numpy_v, scipy_v = _versions()
    header = [
        "// Generated by generate_equiv.py. Do not edit.",
        f"// python={py} numpy={numpy_v} scipy={scipy_v}",
        "// inputs: see the matching *_prototype.py in this directory tree.",
        "",
    ]
    for slug, filename, rust_name in SLUGS:
        mod = _load(slug, filename)
        lines = list(header)
        for const_name, value in mod.equiv().items():
            lines.extend(_emit_const(const_name, value))
            lines.append("")
        (out_dir / rust_name).write_text("\n".join(lines), encoding="utf-8")


def emit_host_scale(out_dir: Path) -> None:
    from numpy.polynomial.polynomial import polyfromroots, polyval
    from scipy import linalg, signal
    from scipy.interpolate import RegularGridInterpolator

    hs = out_dir / "host_scale"
    hs.mkdir(parents=True, exist_ok=True)
    py, numpy_v, scipy_v = _versions()
    eps = float(np.finfo(np.float64).eps)
    tau = 10.0
    meta: list[str] = [
        "// Generated by generate_equiv.py host-scale. Do not edit.",
        f"// python={py} numpy={numpy_v} scipy={scipy_v}",
        f"pub const TAU: f64 = {_rust_scalar(tau, 'f64')};",
        f"pub const EPS: f64 = {_rust_scalar(eps, 'f64')};",
        "",
    ]

    for n in (12, 16, 128):
        a = linalg.hilbert(n)
        b = np.ones(n, dtype=np.float64)
        x = linalg.solve(a, b)
        kappa = float(np.linalg.cond(a))
        _write_f64_le(hs / f"hilbert{n}_a.bin", a)
        _write_f64_le(hs / f"hilbert{n}_b.bin", b)
        _write_f64_le(hs / f"hilbert{n}_x.bin", x)
        meta.append(f"pub const HILBERT{n}_KAPPA: f64 = {_rust_scalar(kappa, 'f64')};")
        meta.append(
            f"pub const HILBERT{n}_KEPS: f64 = {_rust_scalar(kappa * eps, 'f64')};"
        )

    a1024 = _well_conditioned(1024, 0.01)
    b1024 = _well_conditioned(1024, 0.02)
    c1024 = a1024 @ b1024
    rhs1024 = np.ones(1024, dtype=np.float64)
    x1024 = linalg.solve(a1024, rhs1024)
    kappa1024 = float(np.linalg.cond(a1024))
    _write_f64_le(hs / "gemm1024_c.bin", c1024)
    _write_f64_le(hs / "lu1024_x.bin", x1024)
    _write_f64_le(hs / "lu1024_b.bin", rhs1024)
    meta.append(
        f"pub const GEMM1024_KAPPA: f64 = {_rust_scalar(kappa1024, 'f64')};"
    )
    meta.append(
        f"pub const LU1024_KAPPA: f64 = {_rust_scalar(kappa1024, 'f64')};"
    )
    meta.append("")

    roots = np.arange(1.0, 52.0, dtype=np.float64)
    coeffs = np.asarray(polyfromroots(roots), dtype=np.float64)
    poly_x = 20.5
    poly_val = float(polyval(poly_x, coeffs))
    poly_kappa = _eval_kappa(coeffs, poly_x)
    _write_f64_le(hs / "poly52_coeffs.bin", coeffs)
    meta.append(f"pub const POLY_X: f64 = {_rust_scalar(poly_x, 'f64')};")
    meta.append(f"pub const POLY_VAL: f64 = {_rust_scalar(poly_val, 'f64')};")
    meta.append(f"pub const POLY_KAPPA: f64 = {_rust_scalar(poly_kappa, 'f64')};")
    meta.append("")

    tf_num = np.array([1.0], dtype=np.float64)
    tf_w = np.array([0.5, 1.0, 2.0], dtype=np.float64)
    _w, h = signal.freqs(np.flip(tf_num), np.flip(coeffs), worN=tf_w)
    _write_f64_le(hs / "tf_h_re.bin", np.asarray(h.real, dtype=np.float64))
    _write_f64_le(hs / "tf_h_im.bin", np.asarray(h.imag, dtype=np.float64))
    tf_kappa = max(_eval_kappa(coeffs, float(w)) for w in tf_w)
    meta.append(f"pub const TF_KAPPA: f64 = {_rust_scalar(tf_kappa, 'f64')};")
    meta.append("")

    a_stiff = np.diag([-1.0, -1.0e6])
    tmat = np.array([[1.0, 1.0], [0.0, 1.0]], dtype=np.float64)
    a_scr = tmat @ a_stiff @ np.linalg.inv(tmat)
    b_c = np.array([[0.0], [1.0]], dtype=np.float64)
    c_c = np.array([[1.0, 0.0]], dtype=np.float64)
    d_c = np.array([[0.0]], dtype=np.float64)
    dt = 1.0e-6
    ad, _bd, _cd, _dd, _ = signal.cont2discrete(
        (a_scr, b_c, c_c, d_c), dt, method="zoh"
    )
    stiff_kappa = float(np.linalg.cond(a_scr))
    _write_f64_le(hs / "stiff_a.bin", a_scr)
    _write_f64_le(hs / "stiff_ad.bin", np.asarray(ad, dtype=np.float64))
    meta.append(
        f"pub const STIFF_KAPPA: f64 = {_rust_scalar(stiff_kappa, 'f64')};"
    )
    meta.append(f"pub const STIFF_DT: f64 = {_rust_scalar(dt, 'f64')};")
    meta.append("")

    n_g = 1024
    idx = np.arange(n_g, dtype=np.float32)
    grid = idx[:, None] + idx[None, :]
    axes = (
        np.arange(n_g, dtype=np.float32),
        np.arange(n_g, dtype=np.float32),
    )
    interp = RegularGridInterpolator(
        axes, grid, method="linear", bounds_error=False, fill_value=None
    )
    points = np.array(
        [[0.0, 0.0], [10.5, 20.25], [100.0, 200.0], [512.5, 512.5]],
        dtype=np.float32,
    )
    samples = np.asarray(interp(points), dtype=np.float32)
    _write_f32_le(hs / "tensor1024_samples.bin", samples)
    meta.append("pub const TENSOR_POINTS: [[f32; 2]; 4] = [")
    for pt in points:
        meta.append(f"    [{pt[0]:.9g}_f32, {pt[1]:.9g}_f32],")
    meta.append("];")
    meta.append("")

    (out_dir / "host_scale_meta.rs").write_text("\n".join(meta), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Directory for generated *_equiv.rs (omit to print transcripts only)",
    )
    args = parser.parse_args()
    if args.out_dir is None:
        for slug, filename, _rust in SLUGS:
            _load(slug, filename).print_transcript()
            print()
        return
    try:
        emit(args.out_dir)
        emit_host_scale(args.out_dir)
    except ModuleNotFoundError as exc:
        req = ROOT / "requirements.txt"
        raise SystemExit(
            f"missing Python dependency {exc.name!r}. "
            f"Install with: pip install -r {req}"
        ) from exc


if __name__ == "__main__":
    main()
