[alias]

# Development tools
xtask = ["run", "--package", "control-rs-xtask", "--"]
# Git-hooks setup
install-hooks = ["xtask", "install-hooks"]


# Continuous Integration
ci = ["xtask", "ci"]
# Interactive TUI
tui = ["xtask", "tui"]

# On-target ETS infrastructure and target execution aliases
qemu = ["tui", "qemu"]
teensy = ["tui", "teensy"]

# CI → virtual ETS (QEMU) and CI → ETS (board)
qemu-ci = ["ci", "qemu"]
teensy-ci = ["ci", "teensy"]

# Format check helper
fmt-check = ["fmt", "--all", "--", "--check"]
fmt-all = ["fmt", "--all"]

# Clippy Helper
lint = ["clippy", "--workspace", "--lib", "--bins", "--tests", "--examples", "--benches", ]
clippy-json = ["lint", "--message-format=json"]
clippy-ci = ["clippy-json", "--", "-D", "warnings"]

# Coverage helper
coverage = ["tarpaulin", "--verbose", "--workspace"]
coverage-ci = ["coverage", "--color", "never", "--out", "Html", "--out", "Json"]