[alias]

# Development tools
xtask = ["run", "--package", "control-rs-xtask", "--"]

# Continuous Integration
ci = ["xtask", "ci"]
# Interactive TUI
tui = ["xtask", "tui"]

# HIL Test Infrastructure & Target Execution Aliases
qemu = ["xtask", "tui", "qemu"]
teensy = ["xtask", "tui", "teensy"]
ci-qemu = ["xtask", "ci", "qemu"]
ci-teensy = ["xtask", "ci", "teensy"]

# Clippy Helper
clippy-json = ["clippy", "--workspace", "--message-format=json", "--", "-D", "warnings"]

# Coverage helper
coverage = ["tarpaulin", "--workspace", "--verbose", "--color", "never", "--out", "Html", "--out", "Json"]