//! # Numeric Types
//!
//! Defines dimension types and bounds for matrix and tensor storage.
//!
//! This module provides traits and structs to handle both compile-time fixed dimensions
//! and runtime dynamic dimensions, enabling flexible matrix operations.
#![allow(clippy::all)]
#![allow(clippy::use_self)]

/// Defines the base behavior for all dimensions, both static and dynamic.
///
/// This trait serves as a bound for storage matrices, ensuring that dimensions
/// can be queried for their size at runtime.
pub trait Dim: Clone + Copy + PartialEq + Eq + core::fmt::Debug {
    /// Returns the runtime value of the dimension.
    ///
    /// # Returns
    /// * `usize` - The size of the dimension.
    fn value(&self) -> usize;
}

/// Defines a sub-trait exclusively for dimensions known at compile-time.
///
/// Implementors of this trait allow for static allocation of storage, such as
/// fixed-size arrays.
pub trait DimName: Dim + Default {
    /// Represents the compile-time value of the dimension.
    ///
    /// This constant allows for the allocation of fixed-size arrays (e.g., `[T; R::VALUE]`).
    const VALUE: usize;
}

/// Trait for adding dimensions.
pub trait DimAdd<Other> {
    /// The resulting dimension type after addition.
    type Output;
    /// Adds two dimensions.
    fn dimadd(self, other: Other) -> Self::Output;
}

/// Trait for subtracting dimensions.
pub trait DimSub<Other> {
    /// The resulting dimension type after subtraction.
    type Output;
    /// Subtracts two dimensions.
    fn dimsub(self, other: Other) -> Self::Output;
}

/// Trait for multiplying dimensions.
pub trait DimMul<Other> {
    /// The resulting dimension type after multiplication.
    type Output;
    /// Multiplies two dimensions.
    fn dimmul(self, other: Other) -> Self::Output;
}

/// Trait for dividing dimensions.
pub trait DimDiv<Other> {
    /// The resulting dimension type after division.
    type Output;
    /// Divides two dimensions.
    fn dimdiv(self, other: Other) -> Self::Output;
}

/// Trait for finding the maximum of two dimensions.
pub trait DimMax<Other> {
    /// The resulting dimension type (maximum).
    type Output;
    /// Returns the maximum of two dimensions.
    fn dimmax(self, other: Other) -> Self::Output;
}

/// Trait for finding the minimum of two dimensions.
pub trait DimMin<Other> {
    /// The resulting dimension type (minimum).
    type Output;
    /// Returns the minimum of two dimensions.
    fn dimmin(self, other: Other) -> Self::Output;
}

/// Represents a dimension known strictly at compile-time.
///
/// This struct is used to specify fixed dimensions for matrices and vectors, allowing for
/// compile-time checks and optimizations.
///
/// # Generic Arguments
/// * `N` - The size of the dimension.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub struct Const<const N: usize>;

/// Represents a dimension known only at runtime.
///
/// This struct is typically used for dense or sparse storage where the size
/// is determined during execution.
///
/// # Fields
/// * `0` - The size of the dimension.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Dyn(pub usize);

impl<const N: usize> Dim for Const<N> {
    #[inline(always)]
    fn value(&self) -> usize {
        N
    }
}

impl<const N: usize> DimName for Const<N> {
    const VALUE: usize = N;
}

impl Dyn {
    /// Creates a new dynamic dimension with the specified value.
    ///
    /// # Arguments
    /// * `value` - The size of the dimension.
    ///
    /// # Returns
    /// * `Dyn` - A new dynamic dimension instance.
    #[must_use]
    #[inline(always)]
    pub const fn new(value: usize) -> Self {
        Self(value)
    }
}

impl Dim for Dyn {
    #[inline(always)]
    fn value(&self) -> usize {
        self.0
    }
}

// Include the thousands of lines generated by our utility
include!(concat!(env!("OUT_DIR"), "/generated_dim_ops.rs"));
