//! Hardware-in-the-Loop (HIL) testing and benchmarking harness.
//!
//! Provides the context and traits needed for executing tests on hardware
//! and communicating with the host runner.

/// Configuration settings for the HIL runner on the target.
pub struct Settings {
    /// Whether to emit verbose logging.
    pub verbose: bool,
}

/// A trait for reporting test metrics and logs back to the host.
///
/// Implement this trait for your specific communication peripheral (e.g., UART, USB, RTT).
pub trait HostReporter {
    /// Writes a slice of bytes to the host.
    fn write(&mut self, data: &[u8]);
    /// Reads up to `buffer.len()` bytes from the host, returning the number read.
    fn read(&mut self, buffer: &mut [u8]) -> usize;
}

/// A trait for accessing a high-resolution hardware timer.
///
/// Implement this trait using your microcontroller's timer peripherals to provide
/// precise timing for benchmarks.
pub trait HostTimer {
    /// Returns the current time in ticks or microseconds.
    fn now(&self) -> u64;
}

/// The execution context returned by the `#[hil_setup]` macro function.
///
/// This structure holds the configuration and drivers needed by the HIL harness
/// to execute tests and communicate with the host.
pub struct Context<R: HostReporter, T: HostTimer, S = Settings> {
    /// The reporter for communicating with the host.
    pub reporter: R,
    /// The timer for measuring performance.
    pub timer: T,
    /// Configuration settings for the test run.
    pub settings: S,
}

/// A descriptor for a registered test or benchmark.
///
/// This is typically generated by the `#[benchmark]` or `#[hil_test]` macros
/// and placed into a custom linker section.
pub struct TestDescriptor {
    /// The name of the test or benchmark.
    pub name: &'static str,
    /// A function pointer to the test body.
    pub test_fn: &'static dyn Fn(),
}